namespace NerdDinner.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulateCountries : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Countries (Name) VALUES ('Afghanistan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Åland Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Albania')");
            Sql("INSERT INTO Countries (Name) VALUES ('Algeria')");
            Sql("INSERT INTO Countries (Name) VALUES ('American Samoa')");
            Sql("INSERT INTO Countries (Name) VALUES ('Andorra')");
            Sql("INSERT INTO Countries (Name) VALUES ('Angola')");
            Sql("INSERT INTO Countries (Name) VALUES ('Anguilla')");
            Sql("INSERT INTO Countries (Name) VALUES ('Antarctica')");
            Sql("INSERT INTO Countries (Name) VALUES ('Antigua and Barbuda')");
            Sql("INSERT INTO Countries (Name) VALUES ('Argentina')");
            Sql("INSERT INTO Countries (Name) VALUES ('Armenia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Aruba')");
            Sql("INSERT INTO Countries (Name) VALUES ('Australia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Austria')");
            Sql("INSERT INTO Countries (Name) VALUES ('Azerbaijan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Bahamas')");
            Sql("INSERT INTO Countries (Name) VALUES ('Bahrain')");
            Sql("INSERT INTO Countries (Name) VALUES ('Bangladesh')");
            Sql("INSERT INTO Countries (Name) VALUES ('Barbados')");
            Sql("INSERT INTO Countries (Name) VALUES ('Belarus')");
            Sql("INSERT INTO Countries (Name) VALUES ('Belgium')");
            Sql("INSERT INTO Countries (Name) VALUES ('Belize')");
            Sql("INSERT INTO Countries (Name) VALUES ('Benin')");
            Sql("INSERT INTO Countries (Name) VALUES ('Bermuda')");
            Sql("INSERT INTO Countries (Name) VALUES ('Bhutan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Bolivia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Bosnia and Herzegovina')");
            Sql("INSERT INTO Countries (Name) VALUES ('Botswana')");
            Sql("INSERT INTO Countries (Name) VALUES ('Bouvet Island')");
            Sql("INSERT INTO Countries (Name) VALUES ('Brazil')");
            Sql("INSERT INTO Countries (Name) VALUES ('British Indian Ocean Territor')");
            Sql("INSERT INTO Countries (Name) VALUES ('Brunei Darussala')");
            Sql("INSERT INTO Countries (Name) VALUES ('Bulgaria')");
            Sql("INSERT INTO Countries (Name) VALUES ('Burkina Faso')");
            Sql("INSERT INTO Countries (Name) VALUES ('Burundi')");
            Sql("INSERT INTO Countries (Name) VALUES ('Cambodia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Cameroon')");
            Sql("INSERT INTO Countries (Name) VALUES ('Canada')");
            Sql("INSERT INTO Countries (Name) VALUES ('Cape Verde')");
            Sql("INSERT INTO Countries (Name) VALUES ('Cayman Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Central African Republic')");
            Sql("INSERT INTO Countries (Name) VALUES ('Chad')");
            Sql("INSERT INTO Countries (Name) VALUES ('Chile')");
            Sql("INSERT INTO Countries (Name) VALUES ('China')");
            Sql("INSERT INTO Countries (Name) VALUES ('Christmas Island')");
            Sql("INSERT INTO Countries (Name) VALUES ('Cocos (Keeling) Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Colombia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Comoros')");
            Sql("INSERT INTO Countries (Name) VALUES ('Congo')");
            Sql("INSERT INTO Countries (Name) VALUES ('Congo, The Democratic Republic of The')");
            Sql("INSERT INTO Countries (Name) VALUES ('Cook Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Costa Rica')");
            Sql("INSERT INTO Countries (Name) VALUES ('Cote Divoire')");
            Sql("INSERT INTO Countries (Name) VALUES ('Croatia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Cuba')");
            Sql("INSERT INTO Countries (Name) VALUES ('Cyprus')");
            Sql("INSERT INTO Countries (Name) VALUES ('Czech Republic')");
            Sql("INSERT INTO Countries (Name) VALUES ('Denmark')");
            Sql("INSERT INTO Countries (Name) VALUES ('Djibouti')");
            Sql("INSERT INTO Countries (Name) VALUES ('Dominica')");
            Sql("INSERT INTO Countries (Name) VALUES ('Dominican Republic')");
            Sql("INSERT INTO Countries (Name) VALUES ('Ecuador')");
            Sql("INSERT INTO Countries (Name) VALUES ('Egypt')");
            Sql("INSERT INTO Countries (Name) VALUES ('El Salvador')");
            Sql("INSERT INTO Countries (Name) VALUES ('Equatorial Guinea')");
            Sql("INSERT INTO Countries (Name) VALUES ('Eritrea')");
            Sql("INSERT INTO Countries (Name) VALUES ('Estonia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Ethiopia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Falkland Islands (Malvinas)')");
            Sql("INSERT INTO Countries (Name) VALUES ('Faroe Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Fiji')");
            Sql("INSERT INTO Countries (Name) VALUES ('Finland')");
            Sql("INSERT INTO Countries (Name) VALUES ('France')");
            Sql("INSERT INTO Countries (Name) VALUES ('French Guiana')");
            Sql("INSERT INTO Countries (Name) VALUES ('French Polynesia')");
            Sql("INSERT INTO Countries (Name) VALUES ('French Southern Territories')");
            Sql("INSERT INTO Countries (Name) VALUES ('Gabon')");
            Sql("INSERT INTO Countries (Name) VALUES ('Gambia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Georgia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Germany')");
            Sql("INSERT INTO Countries (Name) VALUES ('Ghana')");
            Sql("INSERT INTO Countries (Name) VALUES ('Gibraltar')");
            Sql("INSERT INTO Countries (Name) VALUES ('Greece')");
            Sql("INSERT INTO Countries (Name) VALUES ('Greenland')");
            Sql("INSERT INTO Countries (Name) VALUES ('Grenada')");
            Sql("INSERT INTO Countries (Name) VALUES ('Guadeloupe')");
            Sql("INSERT INTO Countries (Name) VALUES ('Guam')");
            Sql("INSERT INTO Countries (Name) VALUES ('Guatemala')");
            Sql("INSERT INTO Countries (Name) VALUES ('Guernsey')");
            Sql("INSERT INTO Countries (Name) VALUES ('Guinea')");
            Sql("INSERT INTO Countries (Name) VALUES ('Guinea-bissau')");
            Sql("INSERT INTO Countries (Name) VALUES ('Guyana')");
            Sql("INSERT INTO Countries (Name) VALUES ('Haiti')");
            Sql("INSERT INTO Countries (Name) VALUES ('Heard Island and Mcdonald Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Holy See (Vatican City State)')");
            Sql("INSERT INTO Countries (Name) VALUES ('Honduras')");
            Sql("INSERT INTO Countries (Name) VALUES ('Hong Kong')");
            Sql("INSERT INTO Countries (Name) VALUES ('Hungary')");
            Sql("INSERT INTO Countries (Name) VALUES ('Iceland')");
            Sql("INSERT INTO Countries (Name) VALUES ('India')");
            Sql("INSERT INTO Countries (Name) VALUES ('Indonesia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Iran, Islamic Republic of')");
            Sql("INSERT INTO Countries (Name) VALUES ('Iraq')");
            Sql("INSERT INTO Countries (Name) VALUES ('Ireland')");
            Sql("INSERT INTO Countries (Name) VALUES ('Isle of Man')");
            Sql("INSERT INTO Countries (Name) VALUES ('Israel')");
            Sql("INSERT INTO Countries (Name) VALUES ('Italy')");
            Sql("INSERT INTO Countries (Name) VALUES ('Jamaica')");
            Sql("INSERT INTO Countries (Name) VALUES ('Japan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Jersey')");
            Sql("INSERT INTO Countries (Name) VALUES ('Jordan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Kazakhstan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Kenya')");
            Sql("INSERT INTO Countries (Name) VALUES ('Kiribati')");
            Sql("INSERT INTO Countries (Name) VALUES ('Korea, Democratic Peoples Republic of')");
            Sql("INSERT INTO Countries (Name) VALUES ('Korea, Republic of')");
            Sql("INSERT INTO Countries (Name) VALUES ('Kuwait')");
            Sql("INSERT INTO Countries (Name) VALUES ('Kyrgyzstan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Lao Peoples Democratic Republic')");
            Sql("INSERT INTO Countries (Name) VALUES ('Latvia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Lebanon')");
            Sql("INSERT INTO Countries (Name) VALUES ('Lesotho')");
            Sql("INSERT INTO Countries (Name) VALUES ('Liberia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Libyan Arab Jamahiriya')");
            Sql("INSERT INTO Countries (Name) VALUES ('Liechtenstein')");
            Sql("INSERT INTO Countries (Name) VALUES ('Lithuania')");
            Sql("INSERT INTO Countries (Name) VALUES ('Luxembourg')");
            Sql("INSERT INTO Countries (Name) VALUES ('Macao')");
            Sql("INSERT INTO Countries (Name) VALUES ('Macedonia, The Former Yugoslav Republic of')");
            Sql("INSERT INTO Countries (Name) VALUES ('Madagascar')");
            Sql("INSERT INTO Countries (Name) VALUES ('Malawi')");
            Sql("INSERT INTO Countries (Name) VALUES ('Malaysia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Maldives')");
            Sql("INSERT INTO Countries (Name) VALUES ('Mali')");
            Sql("INSERT INTO Countries (Name) VALUES ('Malta')");
            Sql("INSERT INTO Countries (Name) VALUES ('Marshall Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Martinique')");
            Sql("INSERT INTO Countries (Name) VALUES ('Mauritania')");
            Sql("INSERT INTO Countries (Name) VALUES ('Mauritius')");
            Sql("INSERT INTO Countries (Name) VALUES ('Mayotte')");
            Sql("INSERT INTO Countries (Name) VALUES ('Mexico')");
            Sql("INSERT INTO Countries (Name) VALUES ('Micronesia, Federated States of')");
            Sql("INSERT INTO Countries (Name) VALUES ('Moldova, Republic of')");
            Sql("INSERT INTO Countries (Name) VALUES ('Monaco')");
            Sql("INSERT INTO Countries (Name) VALUES ('Mongolia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Montenegro')");
            Sql("INSERT INTO Countries (Name) VALUES ('Montserrat')");
            Sql("INSERT INTO Countries (Name) VALUES ('Morocco')");
            Sql("INSERT INTO Countries (Name) VALUES ('Mozambique')");
            Sql("INSERT INTO Countries (Name) VALUES ('Myanmar')");
            Sql("INSERT INTO Countries (Name) VALUES ('Namibia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Nauru')");
            Sql("INSERT INTO Countries (Name) VALUES ('Nepal')");
            Sql("INSERT INTO Countries (Name) VALUES ('Netherlands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Netherlands Antilles')");
            Sql("INSERT INTO Countries (Name) VALUES ('New Caledonia')");
            Sql("INSERT INTO Countries (Name) VALUES ('New Zealand')");
            Sql("INSERT INTO Countries (Name) VALUES ('Nicaragua')");
            Sql("INSERT INTO Countries (Name) VALUES ('Niger')");
            Sql("INSERT INTO Countries (Name) VALUES ('Nigeria')");
            Sql("INSERT INTO Countries (Name) VALUES ('Niue')");
            Sql("INSERT INTO Countries (Name) VALUES ('Norfolk Island')");
            Sql("INSERT INTO Countries (Name) VALUES ('Northern Mariana Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Norway')");
            Sql("INSERT INTO Countries (Name) VALUES ('Oman')");
            Sql("INSERT INTO Countries (Name) VALUES ('Pakistan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Palau')");
            Sql("INSERT INTO Countries (Name) VALUES ('Palestinian Territory, Occupied')");
            Sql("INSERT INTO Countries (Name) VALUES ('Panama')");
            Sql("INSERT INTO Countries (Name) VALUES ('Papua New Guinea')");
            Sql("INSERT INTO Countries (Name) VALUES ('Paraguay')");
            Sql("INSERT INTO Countries (Name) VALUES ('Peru')");
            Sql("INSERT INTO Countries (Name) VALUES ('Philippines')");
            Sql("INSERT INTO Countries (Name) VALUES ('Pitcairn')");
            Sql("INSERT INTO Countries (Name) VALUES ('Poland')");
            Sql("INSERT INTO Countries (Name) VALUES ('Portugal')");
            Sql("INSERT INTO Countries (Name) VALUES ('Puerto Rico')");
            Sql("INSERT INTO Countries (Name) VALUES ('Qatar')");
            Sql("INSERT INTO Countries (Name) VALUES ('Reunion')");
            Sql("INSERT INTO Countries (Name) VALUES ('Romania')");
            Sql("INSERT INTO Countries (Name) VALUES ('Russian Federation')");
            Sql("INSERT INTO Countries (Name) VALUES ('Rwanda')");
            Sql("INSERT INTO Countries (Name) VALUES ('Saint Helena')");
            Sql("INSERT INTO Countries (Name) VALUES ('Saint Kitts and Nevis')");
            Sql("INSERT INTO Countries (Name) VALUES ('Saint Lucia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Saint Pierre and Miquelon')");
            Sql("INSERT INTO Countries (Name) VALUES ('Saint Vincent and The Grenadines')");
            Sql("INSERT INTO Countries (Name) VALUES ('Samoa')");
            Sql("INSERT INTO Countries (Name) VALUES ('San Marino')");
            Sql("INSERT INTO Countries (Name) VALUES ('Sao Tome and Principe')");
            Sql("INSERT INTO Countries (Name) VALUES ('Saudi Arabia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Senegal')");
            Sql("INSERT INTO Countries (Name) VALUES ('Serbia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Seychelles')");
            Sql("INSERT INTO Countries (Name) VALUES ('Sierra Leone')");
            Sql("INSERT INTO Countries (Name) VALUES ('Singapore')");
            Sql("INSERT INTO Countries (Name) VALUES ('Slovakia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Slovenia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Solomon Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Somalia')");
            Sql("INSERT INTO Countries (Name) VALUES ('South Africa')");
            Sql("INSERT INTO Countries (Name) VALUES ('South Georgia and The South Sandwich Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Spain')");
            Sql("INSERT INTO Countries (Name) VALUES ('Sri Lanka')");
            Sql("INSERT INTO Countries (Name) VALUES ('Sudan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Suriname')");
            Sql("INSERT INTO Countries (Name) VALUES ('Svalbard and Jan Mayen')");
            Sql("INSERT INTO Countries (Name) VALUES ('Swaziland')");
            Sql("INSERT INTO Countries (Name) VALUES ('Sweden')");
            Sql("INSERT INTO Countries (Name) VALUES ('Switzerland')");
            Sql("INSERT INTO Countries (Name) VALUES ('Syrian Arab Republic')");
            Sql("INSERT INTO Countries (Name) VALUES ('Taiwan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Tajikistan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Tanzania, United Republic of')");
            Sql("INSERT INTO Countries (Name) VALUES ('Thailand')");
            Sql("INSERT INTO Countries (Name) VALUES ('Timor-leste')");
            Sql("INSERT INTO Countries (Name) VALUES ('Togo')");
            Sql("INSERT INTO Countries (Name) VALUES ('Tokelau')");
            Sql("INSERT INTO Countries (Name) VALUES ('Tonga')");
            Sql("INSERT INTO Countries (Name) VALUES ('Trinidad and Tobago')");
            Sql("INSERT INTO Countries (Name) VALUES ('Tunisia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Turkey')");
            Sql("INSERT INTO Countries (Name) VALUES ('Turkmenistan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Turks and Caicos Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Tuvalu')");
            Sql("INSERT INTO Countries (Name) VALUES ('Uganda')");
            Sql("INSERT INTO Countries (Name) VALUES ('Ukraine')");
            Sql("INSERT INTO Countries (Name) VALUES ('United Arab Emirates')");
            Sql("INSERT INTO Countries (Name) VALUES ('United Kingdom')");
            Sql("INSERT INTO Countries (Name) VALUES ('United States')");
            Sql("INSERT INTO Countries (Name) VALUES ('United States Minor Outlying Islands')");
            Sql("INSERT INTO Countries (Name) VALUES ('Uruguay')");
            Sql("INSERT INTO Countries (Name) VALUES ('Uzbekistan')");
            Sql("INSERT INTO Countries (Name) VALUES ('Vanuatu')");
            Sql("INSERT INTO Countries (Name) VALUES ('Venezuela')");
            Sql("INSERT INTO Countries (Name) VALUES ('Viet Nam')");
            Sql("INSERT INTO Countries (Name) VALUES ('Virgin Islands, British')");
            Sql("INSERT INTO Countries (Name) VALUES ('Virgin Islands, U.S.')");
            Sql("INSERT INTO Countries (Name) VALUES ('Wallis and Futuna')");
            Sql("INSERT INTO Countries (Name) VALUES ('Western Sahara')");
            Sql("INSERT INTO Countries (Name) VALUES ('Yemen')");
            Sql("INSERT INTO Countries (Name) VALUES ('Zambia')");
            Sql("INSERT INTO Countries (Name) VALUES ('Zimbabwe')");
        }
        
        public override void Down()
        {
        }
    }
}
